// import { describe } from "mocha";
// import chai from "chai";
// window['chai'] = chai;
import "./state.spec";
import "./mutation.spec";
import "./task.spec";
import "./expression.spec";
import "./shop.spec";
import "./fruit.spec";
import "./veggie.spec";